services:
  # PostgreSQL Database
  simpletask-backend-db:
    image: postgres:17.5-alpine
    container_name: simpletask-backend-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  # Redis Cache
  simpletask-backend-redis:
    image: redis:7.4-alpine
    container_name: simpletask-backend-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test:
        ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - backend_network

  # FastAPI Backend
  simpletask-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: simpletask-backend-api
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@simpletask-backend-db:5432/${DB_NAME}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@simpletask-backend-redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENVIRONMENT=development
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      simpletask-backend-db:
        condition: service_healthy
      simpletask-backend-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  backend_network:
    driver: bridge
    name: simpletask_backend_network
